const projects = [
  {
    title: "2D Space Shooter",
    imgUrl: "./galaga.png",
    description:
      "I made this classic style shooter during the foundations section of the Enspiral Dev Academy bootcamp and was not part of the curiculum. Play until you die as there are infinite rounds and enemies. HAVE FUN!",
    href: `https://christopher-alba.github.io/galaga-clone/`,
    tags: ["HTML", "CSS", "Javascript", "jQuery", "Desktop", "Game"],
  },
  {
    title: "Basic Scientific Calculator",
    imgUrl: "./calculator.png",
    description:
      "This project is an extension of an exercise during foundations at EDA. It has basic arithmetic operations, stored temporary memory and other basic functions of a scientific calculator. It also has an ON/OFF button.",
    href: `https://christopher-alba.github.io/calculator/`,
    tags: ["HTML", "CSS", "Javascript", "jQuery", "Desktop", "Mobile"],
  },
  {
    title: "PvP Chess with Assists",
    imgUrl: "./chess.png",
    description:
      "I made this during the last week of foundations at EDA and was not part of the curiculum. It features chess with all the computer assists that prevent any illegal moves based on the original rules of classic chess. Unfortunately, there is no AI (yet).",
    href: `https://christopher-alba.github.io/chess/`,
    tags: ["HTML", "CSS", "Javascript", "jQuery", "Desktop", "Game"],
  },
  {
    title: "Dress the Clown",
    imgUrl: "./clown.png",
    description:
      "This was an extension of an exercise during sprint 5 of foundations at EDA. It features the ability to change the attire of the clown and save it as an image. Have fun mixing and matching!",
    href: `https://christopher-alba.github.io/javascript-carnival/dress-the-clown/dress-the-clown.html`,
    tags: ["HTML", "CSS", "Javascript", "Desktop", "Mobile", "Game"],
  },
  {
    title: "Whack-a-Mole",
    imgUrl: "./mole.png",
    description:
      "This was an extension of an exercise during sprint 5 of foundations at EDA. It is similar to one of those games at a carnival where you smack things that pop out. Have fun clicking moles!",
    href: `https://christopher-alba.github.io/javascript-carnival/whack-a-mole/whack-a-mole.html`,
    tags: ["HTML", "CSS", "Javascript", "Desktop", "Mobile", "Game"],
  },
  {
    title: "EDA Foundations Personal Blog",
    imgUrl: "./blog.png",
    description:
      "I created this blog as part of the EDA foundations curiculum and it contains my reflections on my learning and on myself. If you want to know more about my experience during foundations or you want to know more about me, feel free to visit my blog.",
    href: `https://christopher-alba.github.io/`,
    tags: [
      "HTML",
      "CSS",
      "Bootstrap",
      "Javascript",
      "jQuery",
      "Desktop",
      "Mobile",
      "Blog",
    ],
  },
  {
    title: "To do List with Persisting Memory",
    imgUrl: "./list.png",
    description: `I made this to do list when I was learning from an online bootcamp from Udemy. It features the ability to add and delete lists, as well as ability to add and delete items within a list. Feel free to leave a nice message if you visit ❤.`,
    href: `https://cryptic-shore-73893.herokuapp.com/`,
    tags: [
      "HTML",
      "CSS",
      "Javascript",
      "jQuery",
      "EJS",
      "Express",
      "MongoDB",
      "Mongoose",
      "Mobile",
      "Desktop",
    ],
  },
  {
    title: "Small Scale E-Commerce Site",
    imgUrl: "./janzart.png",
    description: `This project began during week 5 of the EDA bootcamp for my personal project presentation in week 7. It is a simulation of an e-commerce website and all the data inside the postgreSQL database is just seed data.The payment system is running in test mode so no real payments can be processed, only tested. Enjoy your visit ❤.`,
    href: `https://janzart.herokuapp.com/#/`,
    tags: [
      "HTML",
      "CSS",
      "Javascript",
      "Node.js",
      "Express.js",
      "Knex.js",
      "React.js",
      "React-Redux",
      "Semantic-UI-React",
      "Auth0",
      "Stripe",
      "Other React Libraries",
      "Desktop",
      "Mobile",
      "eCommerce",
    ],
  },
  {
    title: "Tourism Site",
    imgUrl: "./tourismNZ.png",
    description:
      "This project is an extension of the project AoteaWoah that I did during the Summer of Tech Create Camp 2020. It is designed to help boost local tourism in NZ and uses a weather API aswell as the google maps API.",
    href: "https://christopher-alba.github.io/AdventureNZ/?#/",
    tags: [
      "HTML",
      "CSS",
      "Javascript",
      "React.js",
      "React-Redux",
      "Semantic-UI-React",
      "Desktop",
      "Mobile",
      "Weather API",
      "Google Maps API",
    ],
  },
  {
    title: "Small Scale Ecommerce V5",
    imgUrl: "./ecommercev5.png",
    description:
      "This is a small scale ecommerce site that allows users to browse products and add them to a shopping cart. Admins can create, update, and delete products in the shop route. To access an admin account, login using username: admin, and password: admin. This site also features a light mode theme and dark mode theme, controlled by a switch.",
    href: "https://ecommercev5.netlify.app/",
    tags: [
      "HTML",
      "Styled Components",
      "Javascript",
      "React.js",
      "Redux",
      "Node.js",
      "Express.js",
      "Mongodb",
      "Semantic-UI-React",
      "Other React Libraries",
      "Desktop",
      "Mobile",
    ],
  },
];

export default projects;
